INSERT INTO medicamento (nombre, descripcion, presentacion) VALUES
('Paracetamol', 'Analgésico y antipirético utilizado para tratar dolores leves a moderados y fiebre.', 'Tabletas 500mg'),
('Ibuprofeno', 'Antiinflamatorio no esteroideo (AINE) utilizado para el dolor, fiebre e inflamación.', 'Cápsulas 200mg'),
('Amoxicilina', 'Antibiótico de la familia de la penicilina usado para tratar infecciones bacterianas.', 'Cápsulas 500mg'),
('Omeprazol', 'Inhibidor de la bomba de protones utilizado para tratar el reflujo gástrico y úlceras.', 'Cápsulas 20mg'),
('Loratadina', 'Antihistamínico utilizado para tratar alergias.', 'Tabletas 10mg'),
('Metformina', 'Medicamento oral para la diabetes tipo 2.', 'Tabletas 850mg'),
('Salbutamol', 'Broncodilatador usado en el tratamiento del asma.', 'Inhalador 100mcg'),
('Clonazepam', 'Benzodiacepina usada para tratar trastornos de ansiedad y convulsiones.', 'Tabletas 2mg'),
('Azitromicina', 'Antibiótico usado para infecciones bacterianas.', 'Tabletas 500mg'),
('Diclofenaco', 'Antiinflamatorio y analgésico.', 'Gel 1%'),
('Losartán', 'Antihipertensivo usado para tratar presión arterial alta.', 'Tabletas 50mg'),
('Ranitidina', 'Usado para reducir la producción de ácido en el estómago.', 'Tabletas 150mg'),
('Cetirizina', 'Antihistamínico para tratar alergias.', 'Tabletas 10mg'),
('Fluoxetina', 'Antidepresivo ISRS.', 'Cápsulas 20mg'),
('Doxiciclina', 'Antibiótico de amplio espectro.', 'Cápsulas 100mg'),
('Enalapril', 'Inhibidor de la ECA usado en hipertensión.', 'Tabletas 10mg'),
('Prednisona', 'Corticosteroide utilizado en enfermedades inflamatorias.', 'Tabletas 5mg'),
('Acetaminofén', 'Analgésico similar al paracetamol, nombre alternativo.', 'Jarabe 250mg/5ml'),
('Naproxeno', 'AINE para dolor e inflamación.', 'Tabletas 250mg'),
('Insulina Glargina', 'Insulina de acción prolongada para diabetes.', 'Solución inyectable 100U/ml');
