spring.application.name=clinica

# Puerto y contexto de la app
server.port=8000
server.servlet.context-path=/clinica/v1

# Conexión a MariaDB en Docker
spring.datasource.url=jdbc:mariadb://localhost:3306/clinica
spring.datasource.username=clinica_user
spring.datasource.password=pPHW/WI51a#9
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MariaDB106Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Pool de conexiones Hikari
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000   # 30s
spring.datasource.hikari.idle-timeout=600000        # 10m
spring.datasource.hikari.max-lifetime=1800000       # 30m